service: nextjs

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs12.x

  environment:
    NODE_ENV: production
    LAMBDA: true
    STAGE: ${self:provider.stage}

functions:
  index:
    handler: index.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
      - cors: true
    layers:
        - arn:aws:lambda:us-east-1:143255761006:layer:dependencies-layer:1

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    keepOutputDirectory: false
    includeModules: false
    packager: 'npm'
    excludeFiles:
      - .serverless
      - .webpack 
      - .dynamodb

  apigwBinary:
    types:
      - '*/*'

package:
  individually: true